### ISSUE TITLE
Getting ClassCastException when following example.

### ISSUE THREAD

**Issue by Kev1000000** [erickok/retrofit-xmlrpc#2]
The library looks great, but following your example always gives me a `java.lang.ClassCastException: libcore.reflect.GenericArrayTypeImpl cannot be cast to java.lang.Class` error when calling this line:

`String[] posts = service.stringList(args).execute().body();`

The response I get back from the server is this:

`D/OkHttp: <?xml version="1.0" encoding="UTF-8"?>
          <methodResponse>
          <params>
D/OkHttp: <param><value><array><data>
          <value><array><data>
          <value><string>I am String #1</string></value>
          <value><string>I am String #2</string></value>
          </data></array></value>
          </data></array></value></param>
          </params>
          </methodResponse>
          <-- END HTTP (360-byte body)`

Any ideas?

**Comment by erickok** [comment]
I'll check today but it might be how you specified the output object. How
does that look like? And what did you define as Retrofit method?

**Comment by Kev1000000** [comment]
```
@XmlRpc("system.xmltest") @POST("/RPC")
Call<String[]> rpcCall(@Body String... fields);
```

**Comment by erickok** [comment]
Your response is not a `String[]` though, but an array of array of strings. It works fine if I use `List<String[]>` instead. By the way, `String[][]` is not supported. Is that something desirable?

**Comment by Kev1000000** [comment]
Haha, I am a dummy.  Thank you!  I will try this out tonight when I return home.

**Comment by Kev1000000** [comment]
I tried updating to..

```
@XmlRpc("system.xmltest") @POST("/RPC")
Call<List<String[]>> rpcCall(@Body String... fields);

List<String[]> posts = service.rpcCall(args).execute().body();
```

With the original output still receiving the same error.  :(  It seems so simple, I really don't know why this would blow up.

**Comment by erickok** [comment]
Hmm that's weird I tested this in a unit test. Is your api open to test
against?

**Comment by Kev1000000** [comment]
Unfortunately no, but it's an ruTorrent server.  I saw your sample to hit rTorrent as well, but I get the same exact cast exception with just requesting the hash and name.

Here are my args...
`String[] args = new String[] {
				"",
				"main",
				"d.hash=",
				"d.get_name="};`

The OkHttp debug output in the original post is what the server returns (with the real hashes/names removed for privacy).

**Comment by erickok** [comment]
Hmm what ruTorrent service are you trying to call? I have alwasy gone straight through the rTorrent XML-RPC api (potentially via the xmlrpc plugin for ruTorrent) and never to ruTorrent itself.

**Comment by Kev1000000** [comment]
A seedbox hosted version of ruTorrent.  I've actually decided to just use an older XML-RPC lib, as I wanted to continue moving forward on the project.  If I can assist further, I'd be happy to help contribute to this, but the other lib is working great at the moment.  Though, I miss retrofit already, heh.  Thanks for the help!

You can close this item if you wish, even though it may still be an issue.

**Comment by erickok** [comment]
No I'd be good to help out. Where call are you trying to make to ruTorrent?

**Comment by Kev1000000** [comment]
I am simply calling `d.multicall2` with the following params...

`new String[]{ "",
                "main",
                "d.hash=",
                "d.get_name="};`

**Comment by erickok** [comment]
Wait... so you are trying to query rTorrent, not ruTorrent. You can see the RtorrentTest for several examples.

**Comment by Kev1000000** [comment]
I have looked over RtorrentTest extensively and have tried calling the same with the above error.  It's most likely something I was doing (though I verified my code was the same as RtorrenTest where it mattered).  I know it makes no sense, heh.

ruTorrent is simply the web GUI of rTorrent, and the XML-RPC API fires back into rTorrent, so the calls are nearly the same.

**Comment by erickok** [comment]
Well they are not so much 'nearly the same' as you literally would communicate directly to rTorrent OR use the xmlrpc plugin (which is the exact same api). Do you use the latter? I mean, what is your actual endpoint?

**Comment by Kev1000000** [comment]
Yeah, I use the latter (xmlrpc) plugin.  Though, must of this shouldn't matter, as the output (which I pasted in the OG post) from OkHttp should be able to be parsed, especially if your unit test with the lib passed successfully.  To me, that's the real mind-boggle.
