### ISSUE TITLE
Issue when I try to send an hashmap

### ISSUE THREAD

**Issue by RiccardoForniz** [erickok/retrofit-xmlrpc#3]
Hello, I have a problem when I try to send an hashmap through xmlrpc.
for example I want to send this kind of param:
HashMap<String,Object> map, it contain [key,value:key,value:key,value:etc], when I try to convert it in an Object[] before call retrofit, the library not parse the xml as i whish.
Do I make any mistake?

this is the parsed xml from Xml-rpc lib

<methodCall>
    <methodName>Test</methodName>
    <params class="java.util.ArrayList">
       <param>
          <value class="nl.nl2312.xmlrpc.types.StructValue">
             <struct/>
          </value>
       </param>
    </params>
 </methodCall>

Let me know.
Thank you

**Comment by erickok** [comment]
I'n not sure if I support Maps, to be honest. Let me check.

**Comment by erickok** [comment]
Indeed I do not support it. I can add that. How does a request look like exactly? And a response?

**Comment by RiccardoForniz** [comment]
ok Then, the request should be like that:
[request.txt](https://github.com/erickok/retrofit-xmlrpc/files/2510461/request.txt)

The response as Map seems already parsed well.

Let me know

**Comment by erickok** [comment]
Thanks; I'll take a look soon.

**Comment by erickok** [comment]
Try version 1.1 where I added support for `Map`s.

**Comment by RiccardoForniz** [comment]
Thanks Eric.
