### ISSUE TITLE
Array of structs cannot be empty?

### ISSUE THREAD

**Issue by alexsaalfeld** [erickok/retrofit-xmlrpc#8]
Hi,
I am receiving an array of structs that converted using the `@MemberName` annotation
```
    @JvmField
    @MemberName("items")
    var items: Array<Item>? = null
```
This works fine as long as I the array has items, however, if the array is empty I get the following message:  
`"Item[] types are not supported by XML-RPC"`  
Here's the XML data:
```
<member>
  <name>items</name>
  <value>
    <array>
      <data/>
    </array>
  </value>
</member>
```
Looking at the code of ArrayValue this actually seems not to be supported. Can this be fixed or am I doing something wrong here?  
Thank you!

**Comment by erickok** [comment]
Hmm sounds like it should be supported. I'll get back to you about this. Have to check if I can reproduce.

**Comment by erickok** [comment]
Sorry for the delay.

Indeed empty arrays were not supported, and without good reason. I just pushed a fix with support for empty arrays.
